version: '3.9'
services:
  web:
    build: ./rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    ports: 
      - 30001:3001
    volumes:
      - ./rails/my-app:/my-app
    depends_on:
      - db
  react:
    build: ./react
    tty: true
    ports: 
      - 3000:3000
    volumes:
      - ./react/my-app:/my-app
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: user
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
   