# ./config/auth0.yml
development:
  auth0_domain: dev-4ak2q3wn.us.auth0.com
  auth0_client_id: lv3w0ZX1xxAQ3xouH20ODQECISdzvkhx
  auth0_client_secret: H9ysT4QhUpJZ2TWIUymfYM3PluuKHZm-p8kRXZDMXqkec8K3KyGhSxzOmWC0WGhv